# Generated by Django 4.0 on 2021-12-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
    ]
