# Generated by Django 4.0 on 2021-12-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_comment_content_alter_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
