# Generated by Django 4.0 on 2021-12-26 14:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_alter_post_intro_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 14, 14, 51, 475226, tzinfo=utc), verbose_name='date published'),
        ),
    ]
